version: "2"
services:
  dev:
    command: yarn run dev
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
    environment:
      NODE_ENV: development
      PORT: 8080
      LOG_LEVEL: debug
      LND_GRPC_HOST: "172.18.0.3:10009"
      LND_TLS_CERT: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNKVENDQWN5Z0F3SUJBZ0lRRXFhWVhoaGkwY0lHSG1pSUlOYy9WREFLQmdncWhrak9QUVFEQWpBeE1SOHcKSFFZRFZRUUtFeFpzYm1RZ1lYVjBiMmRsYm1WeVlYUmxaQ0JqWlhKME1RNHdEQVlEVlFRREV3VmhiR2xqWlRBZQpGdzB5TWpBMU1qWXlNVEU0TXpoYUZ3MHlNekEzTWpFeU1URTRNemhhTURFeEh6QWRCZ05WQkFvVEZteHVaQ0JoCmRYUnZaMlZ1WlhKaGRHVmtJR05sY25ReERqQU1CZ05WQkFNVEJXRnNhV05sTUZrd0V3WUhLb1pJemowQ0FRWUkKS29aSXpqMERBUWNEUWdBRVA4RUtHbzZOVUxrbHJ2eHBsd3hZb1B1MmlrdDFvYy9oUnNqNHk1T3lqUGIvRnhCMgpJd015bE1uSDJESDJ1aENtcm1lL0dEZThiOS9pNitEaXhLMnc3YU9CeFRDQndqQU9CZ05WSFE4QkFmOEVCQU1DCkFxUXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEUKRmdRVWhhNGFQSHN4M0JQWWRQT1hZOVh5YVNvNTJ3Y3dhd1lEVlIwUkJHUXdZb0lGWVd4cFkyV0NDV3h2WTJGcwphRzl6ZElJRllXeHBZMldDRG5CdmJHRnlMVzR5TFdGc2FXTmxnZ1IxYm1sNGdncDFibWw0Y0dGamEyVjBnZ2RpCmRXWmpiMjV1aHdSL0FBQUJoeEFBQUFBQUFBQUFBQUFBQUFBQUFBQUJod1NzRXdBRk1Bb0dDQ3FHU000OUJBTUMKQTBjQU1FUUNJQjRpS0c4UDFlVjRBa0N3UnRQRGczOTlQcStpUGNvQURxOHV1NCtieXdxL0FpQkVEekxUZjR2Ygo5VXlxZkc0d2xkL1BvNmE4RmJPN215VlBCRTc1UGU2azBRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
      LND_MACAROON: "AgEDbG5kAvgBAwoQYg/zLuXeWNif5ar1oqC0QBIBMBoWCgdhZGRyZXNzEgRyZWFkEgV3cml0ZRoTCgRpbmZvEgRyZWFkEgV3cml0ZRoXCghpbnZvaWNlcxIEcmVhZBIFd3JpdGUaIQoIbWFjYXJvb24SCGdlbmVyYXRlEgRyZWFkEgV3cml0ZRoWCgdtZXNzYWdlEgRyZWFkEgV3cml0ZRoXCghvZmZjaGFpbhIEcmVhZBIFd3JpdGUaFgoHb25jaGFpbhIEcmVhZBIFd3JpdGUaFAoFcGVlcnMSBHJlYWQSBXdyaXRlGhgKBnNpZ25lchIIZ2VuZXJhdGUSBHJlYWQAAAYgH5ZXTLeEtdv/5d6yXbzbEStisodq07z/rGe4O6ZKDmw="
networks:
  default:
      external:
          name: 1_default