version: "2"
services:
  dev:
    command: yarn run dev
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
    environment:
      NODE_ENV: development
      PORT: 8080
      LOG_LEVEL: debug
      LND_GRPC_HOST: "172.18.0.3:10009"
      LND_TLS_CERT: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNKekNDQWN5Z0F3SUJBZ0lRTVZ2cTYxaGU2SXFTay90Rk5YZVhQekFLQmdncWhrak9QUVFEQWpBeE1SOHcKSFFZRFZRUUtFeFpzYm1RZ1lYVjBiMmRsYm1WeVlYUmxaQ0JqWlhKME1RNHdEQVlEVlFRREV3VmhiR2xqWlRBZQpGdzB5TWpBek1UY3lNek00TVRWYUZ3MHlNekExTVRJeU16TTRNVFZhTURFeEh6QWRCZ05WQkFvVEZteHVaQ0JoCmRYUnZaMlZ1WlhKaGRHVmtJR05sY25ReERqQU1CZ05WQkFNVEJXRnNhV05sTUZrd0V3WUhLb1pJemowQ0FRWUkKS29aSXpqMERBUWNEUWdBRTgyd28vRm9WS2lNNVFmWUhLVnpiNVFGNmJPekRzSW5ITGRxZkNJQTF4aWVKTm90MApDWEJGYm9FWEFyU25PcVJGdkVhUk5yczdsaXA4OWw5SHcxYjhrS09CeFRDQndqQU9CZ05WSFE4QkFmOEVCQU1DCkFxUXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEUKRmdRVTN3TGptckZ2MUJqb0ZDZVllVU1qWDNhZjJOZ3dhd1lEVlIwUkJHUXdZb0lGWVd4cFkyV0NDV3h2WTJGcwphRzl6ZElJRllXeHBZMldDRG5CdmJHRnlMVzR4TFdGc2FXTmxnZ1IxYm1sNGdncDFibWw0Y0dGamEyVjBnZ2RpCmRXWmpiMjV1aHdSL0FBQUJoeEFBQUFBQUFBQUFBQUFBQUFBQUFBQUJod1NzRXdBRk1Bb0dDQ3FHU000OUJBTUMKQTBrQU1FWUNJUUN3Umpjb2pSNVhUNzBnVi9aVVdnKzFzUTFxTUVlcThTb1ZtUVYxMm5sNTVRSWhBUDhGckJFSgpnUlRHaDgwSy9ib0VVVkRra1pCWVI0RTBWK3BWeVdpZ29aM3EKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
      LND_MACAROON: "AgEDbG5kAvgBAwoQfpOes6IwNtOFlKIQt6p2KBIBMBoWCgdhZGRyZXNzEgRyZWFkEgV3cml0ZRoTCgRpbmZvEgRyZWFkEgV3cml0ZRoXCghpbnZvaWNlcxIEcmVhZBIFd3JpdGUaIQoIbWFjYXJvb24SCGdlbmVyYXRlEgRyZWFkEgV3cml0ZRoWCgdtZXNzYWdlEgRyZWFkEgV3cml0ZRoXCghvZmZjaGFpbhIEcmVhZBIFd3JpdGUaFgoHb25jaGFpbhIEcmVhZBIFd3JpdGUaFAoFcGVlcnMSBHJlYWQSBXdyaXRlGhgKBnNpZ25lchIIZ2VuZXJhdGUSBHJlYWQAAAYgW2AYMRHmWO5S3sEdLSInFmiBsb0Oc5sSHMFsCyScU6g="
networks:
  default:
      external:
          name: '2_default'